version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: [--auth]
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./mongo/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
      - ./../mongo-database/data/db:/data/db
